substitutions:
  name: "m5-dial"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password  

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: smarthomeyourself.m5_dial
    version: "1.0"

  platformio_options:
    lib_deps:
      - WiFi
      - SPI
      - FS
      - Wire
      - EEPROM
      - ArduinoJson
      - m5stack/M5Unified@0.1.14
      - m5stack/M5Dial

external_components:
  - source:
      type: git
      url: https://github.com/SmartHome-yourself/m5-dial-for-esphome/
      ref: main
    components: [shys_m5_dial]

dashboard_import:
  package_import_url: github://SmartHome-yourself/m5-dial-for-esphome/shys-m5-dial.yaml@main
  import_full_config: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  level: DEBUG

api:
ota:
  platform: esphome

improv_serial:
captive_portal:

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    password: "12345678"

packages:
  m5_tough_package:
    url: https://github.com/SmartHome-yourself/m5-dial-for-esphome
    ref: main
    file: shys-m5-dial.yaml
    refresh: 1h

shys_m5_dial:
  name: Dial
  screen_off_time: 45000
  rotary_step_width: 5
  long_press_duration: 1200
  font: FreeSans12pt7b
  font_factor: 1

  devices:
    lights:
      - entity: light.office_lamp
        name: Office
        modes:
          dimm_mode:
            enable: true
            rotary_step_width: 5
          rgb_mode: 
            enable: true
            rotary_step_width: 10
          white_mode: 
            enable: true
            rotary_step_width: 100
            min_kelvin: 2500
            max_kelvin: 7000
            
      - entity: light.crystal_lamp
        name: Crystal Lamp
        modes:
          dimm_mode:
            enable: true
            rotary_step_width: 5        

    switches:
      - entity: switch.sonoff_1001fbed64_1
        name: Kitchen
                    
    covers:
      - entity: cover.blind_tilt_8ec9
        name: Stair Blinds
        modes:
          position_mode:
            rotary_step_width: 5

    fans:
      - entity: fan.lr_fan
        name: LR Fan
        modes:
          speed_mode:
            changeable_direction: true
            rotary_step_width: 10

    media_player:
      - entity: media_player.office_audio
        name: Office Audio
        modes:
          play_mode:
            rotary_step_width: 2
          source_mode:
            rotary_step_width: 1
            sources:
              - name: 1Live
                content_id: 1Live
                content_type: TUNEIN
              - name: WDR2
                content_id: "http://wdr-wdr2-bergischesland.icecast.wdr.de/wdr/wdr2/bergischesland/mp3/128/stream.mp3"
                content_type: custom

    lock:
      - entity: lock.front_door
        name: Front Door
        modes:
          lock_mode:
            rotary_step_width: 1
            open_on_button: false